sonar.projectKey=lecctdemo2
sonar.projectName=lectdemo2
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes
sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000/
sonar.token=squ_7dbdbd1f145e6a37fa9bca419c7fe306017af18e